language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: lX1NgWVjI6KNFIBSdBz2n84ENRJWVJjtTWzUAPgrLYlirQvBivc0E5ahhTl/9cXVSK6+i4DbBkz5TFZJkAi/1YzleFpY6rhhTmFrn351+EioGN5i51kZRtee32/CctMHOBwl1WmGNzUCVbohlDunyZiGnDDLbPm63T4a71B1NawIW6rXqiNhMm/nBqkUmG2pvqCcFflLDXkwo/70jNP18qoVbrHNDzlsn7+Bu9LXpS0qXyZV0WHrqH4jsFzAJTRHkvtAIM+u4G2ikUnAlw3uBsS65++C6+Oc73cjRHhjWyrsiGT0290pEE0ZiijWw8a0SLIaYoVINrrv0R6JvLlnc06K0e72skQE6EzOBNrEB5n2jugawzODzn2Hp0b9XG+h8E35pk0W0WnUY6NxZzaIomeYFyCZvQ6T+v3jeMmz3HuDcHuqZvTyh1XIRTiLTa07a903DLqo5TMx/ihg/Pc1iLoXJiVxAiHaCAn3FM5eDk22k6MBTHViMOp6Wf+uobnLicY6wtKcs+b3dLduHrl6Cr+1nreWd3HbvhI4KRNem8Rd0PAmn8SKOXwzy5Hu2E+D+C2PasdTVacgisYAZRUz1T249ajSKo8tjX7vxttS6tBqltJJUrKpues0hg/44kJQRcKkt2viKamjGjvZ0boBEtc4ryRcwyg6EW6ZjYrHCUU=
  app: obscure-garden-2964
  on:
    repo: yosukeiseki/rakuten_enpit_example
  branch: master